package seliv.aoc.aoc2020;

/**
 * User: aselivanov
 * Date: 12/2/2020
 * Time: 7:57 AM
 */
public class Aoc2 {
    public static void main(String[] args) {
        String[] ss = IN.split("\n");
        int res = 0;
        for (String s : ss) {
            String[] a = s.split(" ");
            String[] mm = a[0].split("\\-");
            char c = a[1].charAt(0);
            String pwd = a[2];
            int low = Integer.parseInt(mm[0]);
            int high = Integer.parseInt(mm[1]);

//            int inc = 0;
//            for (int i = 0; i < pwd.length(); i++) {
//                if (c == pwd.charAt(i)) {
//                    inc++;
//                }
//            }
//            if ((low <= inc) && (inc <= high)) {
//                res++;
//            }
            if ((high - 1 < pwd.length()) && (low - 1 < pwd.length()) && (pwd.charAt(low - 1) == c) && (pwd.charAt(high - 1) != c) ||
                    (high - 1 < pwd.length()) && (low - 1 < pwd.length()) && (pwd.charAt(high - 1) == c) && (pwd.charAt(low - 1) != c)) {
                res++;
            }
        }
        System.out.println("res = " + res);
    }

//    private static final String IN = "1-3 a: abcde\n" +
//            "1-3 b: cdefg\n" +
//            "2-9 c: ccccccccc";


    private static final String IN = "1-7 q: qqqqxvqrkbqqztlqlzq\n" +
            "1-3 q: cqbm\n" +
            "15-16 h: hhhhhhhhhhhhhhbsh\n" +
            "4-16 x: xvbxswpnvxtnfjrxxx\n" +
            "6-7 v: kbbvnswp\n" +
            "17-18 h: hhhvhhhhhhhhhhhhhh\n" +
            "1-7 w: twftdrb\n" +
            "4-5 t: wcjtfpt\n" +
            "3-9 f: mbfvfptbfq\n" +
            "3-10 x: xfxxxxxxxv\n" +
            "5-11 p: ppvhkgpmwfjp\n" +
            "5-8 c: cbhhrtsbpf\n" +
            "13-14 t: ttttltttgttttvht\n" +
            "11-16 m: mmmmmmmrmmdmmmmxmmm\n" +
            "3-13 b: bbbbbgbbbbbkkbvd\n" +
            "7-10 d: ndddwdmdddhddv\n" +
            "4-7 d: gcndnddkwhd\n" +
            "14-18 z: zzzzzzzzzzzzzvzzzzzz\n" +
            "5-6 c: mfcwccckdccfmzc\n" +
            "9-14 p: bppzpwhzdgnpnh\n" +
            "11-19 q: jqhqqqqqqqmfqqqqqqqq\n" +
            "5-6 h: kqhpgl\n" +
            "15-18 w: wwwwwwwwwwwwwwqwwqw\n" +
            "2-10 m: qmmmmtphbrw\n" +
            "10-20 k: jxlnkxnkhlkgkzhxbdvg\n" +
            "8-9 c: ccccccccc\n" +
            "12-19 k: vlkkkkklkzkkzkkckkfk\n" +
            "13-14 s: bsfssqsscsssdj\n" +
            "11-13 p: rmpdppplgcnpwxd\n" +
            "9-16 c: ccccccccrclccqcgcc\n" +
            "3-8 s: snsssmssdns\n" +
            "13-19 t: ttttttttttttttttttwt\n" +
            "7-8 q: dqqqdqqqqnqdq\n" +
            "10-11 w: wwwvwwvhwtvwwwmw\n" +
            "3-6 b: bbsnbpbckbb\n" +
            "1-4 g: gggjg\n" +
            "6-8 b: jvrqbbmb\n" +
            "2-6 t: cvdtzn\n" +
            "3-4 v: vvmd\n" +
            "2-8 z: vmwhtskz\n" +
            "2-6 b: jbrbjbs\n" +
            "1-2 d: ndzwd\n" +
            "17-20 r: xjfmlrrjcnnrmkvhrpwr\n" +
            "8-10 q: qqqwqqqqqdl\n" +
            "2-5 p: phppxpppppppp\n" +
            "9-10 z: zzzzzznzzz\n" +
            "8-9 k: phgksffkrfgp\n" +
            "11-13 w: wwwwwwwwwwnwz\n" +
            "9-11 k: krkkkkqkkkkskkk\n" +
            "19-20 d: dmcwfddgdddvdffdhdld\n" +
            "8-11 f: bflfqsffvfdffmfpfqf\n" +
            "6-10 v: wwqvvvjvrd\n" +
            "4-5 v: vvdvw\n" +
            "3-4 h: hdhh\n" +
            "9-10 d: dndfdddddd\n" +
            "3-13 n: nnfnnnnnnnnnnnnnnmnn\n" +
            "5-12 b: zwqcbkfcbbnbb\n" +
            "5-15 q: qqrdqqqmqqnqqnjkqqqw\n" +
            "6-8 l: vfllklxllclll\n" +
            "3-4 h: hchh\n" +
            "12-16 b: bbbbbbbbbbbhwbbtgbs\n" +
            "4-10 p: ppwxplpppp\n" +
            "4-5 s: szhss\n" +
            "8-10 w: tvdtvbwnlfvkspxp\n" +
            "4-9 z: zzznnkzwdzrz\n" +
            "5-14 p: pppppppppppjpp\n" +
            "6-7 n: hnnnnqnn\n" +
            "1-4 q: qqdqqq\n" +
            "7-8 w: wwwwwwbpww\n" +
            "3-10 x: xfxxnxjxxxpx\n" +
            "5-19 m: kmqhgpjdszvgrfrdlhm\n" +
            "10-12 k: kqqzkkkkkkkk\n" +
            "4-7 l: llpqcgmll\n" +
            "4-5 p: rwppp\n" +
            "2-6 q: mqqhrsdk\n" +
            "7-10 m: cmmvscmmkm\n" +
            "9-18 k: kkkkkzkkqdpkdlkjpgk\n" +
            "2-7 m: xmglcvmkmln\n" +
            "8-12 n: nnnnnnnfjnnbn\n" +
            "4-5 n: nnnnn\n" +
            "13-17 z: zzzzzzzzzzzzkzzzz\n" +
            "1-5 t: mfftmn\n" +
            "2-3 n: nskh\n" +
            "11-18 s: sjssgsssfstzsbhnsw\n" +
            "14-16 d: pgxrmlxdthpdndfdt\n" +
            "2-3 h: hhhhh\n" +
            "3-4 s: hssn\n" +
            "7-9 f: fffffcmff\n" +
            "2-4 s: srwbvhnlqssdpsssx\n" +
            "3-4 v: vvvvvsvxvvh\n" +
            "12-13 x: xxxxsxsxxdxmpjxlxxf\n" +
            "15-16 m: cjcmmmmgdmbnmcmm\n" +
            "8-11 l: hsjlnlvlfchgjlrdl\n" +
            "9-11 k: kkknkkdkdkkk\n" +
            "5-6 q: qgqqfpq\n" +
            "16-19 w: wwwwfwwwwwwwvlwwwtw\n" +
            "2-13 n: nnnjngnwgldsnrnrr\n" +
            "5-6 x: qwbpxx\n" +
            "4-5 x: xxxhx\n" +
            "11-13 t: ctpskdtbwbtkstfj\n" +
            "2-8 z: jwznsgln\n" +
            "17-18 r: rrrrrrrrrrrrrrrrwnr\n" +
            "7-12 v: bkpvwzzsdnsd\n" +
            "5-7 h: hxxnpzh\n" +
            "7-8 z: zzzzzzxs\n" +
            "3-7 z: hzstpkrlht\n" +
            "7-10 p: ppgkppnpdppj\n" +
            "10-11 g: gghhgvgggwf\n" +
            "9-11 q: qqqqxqqqqpqqqq\n" +
            "2-3 r: qrrfr\n" +
            "3-8 x: xvxzsxtxgxb\n" +
            "11-14 q: fbqtzvjdqqhqqrqjrqq\n" +
            "11-16 c: cccpccccccscwccfccn\n" +
            "9-11 m: snmmmcmmsmmmmkm\n" +
            "2-11 m: mmmczqsmclmrvmbzlv\n" +
            "10-15 z: zzzzzzzzzjzzzzkjzzm\n" +
            "3-13 j: jjxjjjjwjjjjbjjjdjjd\n" +
            "7-10 j: sjjqjjvzjjcjrh\n" +
            "8-9 x: xxxxxxxzxxx\n" +
            "4-11 n: nnmnmndfnhqnhnn\n" +
            "16-19 v: kntvxvvvvpvvvvghkzp\n" +
            "6-9 b: pbbbxxjfqvngbvbb\n" +
            "16-17 j: jjjjjjjjmjjjjjjjjj\n" +
            "2-3 t: wttttttt\n" +
            "10-15 c: cccccccccgpcccccc\n" +
            "7-10 j: jjjjjjqjjrj\n" +
            "1-7 f: cffffftfff\n" +
            "8-14 r: rrnrrrrrfrrgscrmr\n" +
            "1-12 b: jbbbjbkwbgbb\n" +
            "13-16 m: mmxmmmmmwmmwmfmmmhbm\n" +
            "1-9 s: fsssssssqs\n" +
            "8-15 q: pxqqqqvbqqsbqzjngkv\n" +
            "3-4 w: wkspxwm\n" +
            "1-7 h: gkfhhhjhhhch\n" +
            "1-4 w: sqrnwwgwqdw\n" +
            "2-6 d: dpdwdld\n" +
            "2-3 m: mmmmm\n" +
            "4-6 p: pppspp\n" +
            "2-7 c: ctcglxx\n" +
            "11-13 x: xxqxxxxxxxxxxd\n" +
            "7-9 c: cgccccbcrc\n" +
            "6-9 p: xspppkppprp\n" +
            "4-5 v: vvfqrv\n" +
            "15-19 l: llwllllllfllllglllcl\n" +
            "10-17 v: vvvvvvvvvgvvvvvvk\n" +
            "11-14 s: sstngtbhsfsgds\n" +
            "3-4 c: dxklc\n" +
            "6-7 l: lllllll\n" +
            "8-10 w: wwwwwwxtwkwnw\n" +
            "3-4 l: sgllkmdpzgzvllzv\n" +
            "7-17 w: zdfsdmwbphwhzwrxww\n" +
            "2-12 l: rbwfpnmzgtsl\n" +
            "3-6 s: qssdwlfbnm\n" +
            "5-16 f: fffffffffffffffzff\n" +
            "12-14 l: lllfllllldlllljll\n" +
            "14-19 x: pxxxxxxxqxxxxxxxkxwx\n" +
            "12-14 b: bbbbbbbbbbbrbnbbbb\n" +
            "2-12 j: trjqljjgrjjq\n" +
            "1-10 q: qqqqqqqqqqqqq\n" +
            "1-6 t: jttttrtt\n" +
            "1-2 v: rpvfcxhcgx\n" +
            "4-5 r: frsrr\n" +
            "1-6 v: jvvvvqvvvv\n" +
            "2-4 v: tvvb\n" +
            "4-5 h: hhchhzhqhcvh\n" +
            "8-9 c: ccphccccccc\n" +
            "13-15 c: cccbccccccxccxclcscc\n" +
            "5-6 b: bbkbpczbs\n" +
            "10-16 g: gdgggggggggggggggg\n" +
            "1-11 f: fmffxfffgcfwfffbzff\n" +
            "3-13 m: mzmmkmntbmmmmcz\n" +
            "1-2 g: xkgq\n" +
            "10-12 r: rbrmrrrrrwrrhrqvkr\n" +
            "7-8 m: wbbmmmmmfmm\n" +
            "3-4 l: dsnt\n" +
            "4-5 k: kkkkkkk\n" +
            "16-17 r: rrrrcrgrrmqwjrpwmtr\n" +
            "15-17 z: zzzzzzzzzzzzzzzzzzz\n" +
            "13-15 b: zbbbbbbbbbbttbbb\n" +
            "8-13 w: twrwwwlwtwwww\n" +
            "10-11 w: wwwwwwwwwwwwwwwwww\n" +
            "4-6 b: pxvqbb\n" +
            "5-8 n: wnnnznngw\n" +
            "4-9 q: njjqqkrlq\n" +
            "10-15 c: cckhfccdhfccccj\n" +
            "10-15 c: ccrktcccgccgccz\n" +
            "1-5 s: dvssx\n" +
            "2-3 w: wwnw\n" +
            "3-4 n: nnnnc\n" +
            "7-16 n: tdlhmgsqknfnwgnnwmn\n" +
            "9-11 z: zgdzzzzwfgjwzzzm\n" +
            "4-5 f: ffpffff\n" +
            "3-6 f: fvgfcff\n" +
            "5-6 f: fkffhhlhrfg\n" +
            "7-13 g: gtflglggggwbg\n" +
            "4-5 w: wwdwrw\n" +
            "8-10 w: hwpzzwwwjbqfww\n" +
            "5-11 f: ftgfffffffpqffffffff\n" +
            "6-7 f: fffffml\n" +
            "6-12 j: jjtjjtjjjzjzjh\n" +
            "4-6 h: phwtrn\n" +
            "10-14 l: lllllllllcllll\n" +
            "6-7 d: hdwxdsk\n" +
            "13-18 w: kwwwwwwwwwwwwwwjwww\n" +
            "3-8 q: bpqtzmqqljll\n" +
            "1-3 c: cccds\n" +
            "4-5 m: mmmmzd\n" +
            "4-7 c: cccjcck\n" +
            "4-6 t: ctdvts\n" +
            "3-10 x: xsxrxshzjxrt\n" +
            "3-6 j: wljvmxqzrjhctx\n" +
            "4-5 v: vwvvcld\n" +
            "8-9 l: blllllvllglllll\n" +
            "4-14 j: jjjjjjjxxsjmjjjjj\n" +
            "8-12 v: bvvvvvvqvvvbvv\n" +
            "2-6 g: pgsgcglt\n" +
            "1-4 g: qggs\n" +
            "7-9 h: phchhpxhqhhh\n" +
            "5-7 z: czzjzrnq\n" +
            "3-4 k: kkkw\n" +
            "2-3 v: vjfv\n" +
            "7-11 v: slrrxhrhnvvk\n" +
            "7-10 t: czhvlfwthc\n" +
            "2-17 m: zmmmmtbmzlwmmmmslbm\n" +
            "1-4 m: fmjz\n" +
            "6-8 d: sdddddddddw\n" +
            "2-5 h: pnfkhrwchvc\n" +
            "2-4 r: brsrktfkqdlhzvvsfhf\n" +
            "3-4 n: qnknnn\n" +
            "7-10 f: rvnzfmfzrfdqkffc\n" +
            "2-5 x: hxxqxkxxw\n" +
            "1-7 w: wwqzwkww\n" +
            "2-3 s: ssps\n" +
            "8-16 d: ddjdddddddddbddddd\n" +
            "10-12 d: dddxddddwldfsd\n" +
            "1-6 v: skcvcwjf\n" +
            "2-7 g: ggggzlggjgwg\n" +
            "2-5 j: rjzfjqjzjtjkfp\n" +
            "15-17 f: bqslszncqcvrpfrff\n" +
            "2-13 d: xcddddddddwdzdmddzd\n" +
            "1-9 l: lllmllxlljlxhll\n" +
            "10-17 p: msbwpcprpppnsbpppzk\n" +
            "2-13 v: vwdvvrsjrvvvpcvvv\n" +
            "5-9 c: xscgtfxjbchcp\n" +
            "4-6 g: jghgfg\n" +
            "7-8 v: vvvvnvvv\n" +
            "10-12 z: zzzzzmzzhbxz\n" +
            "11-17 b: fknnqwzpgbbqnxkckj\n" +
            "1-3 h: zgbpdwdnmmhbnqxm\n" +
            "4-6 t: httsznfnx\n" +
            "5-10 f: fflfffrfvxvgdq\n" +
            "1-3 r: zrrrrrrrrnrr\n" +
            "5-7 k: kkkkkkkkkkk\n" +
            "6-7 r: rrrrrfgrrrz\n" +
            "3-12 s: sssssssssssssss\n" +
            "3-5 t: ttjdtt\n" +
            "3-4 s: zzhslfrtwsj\n" +
            "5-6 d: dddpddv\n" +
            "1-7 q: bqqqdqpqq\n" +
            "10-13 s: ssstscpsslsrsssds\n" +
            "7-8 r: lrrrrrrr\n" +
            "5-10 z: jzfwzlzjlz\n" +
            "3-8 g: grpggggg\n" +
            "1-7 c: jccccjvcc\n" +
            "12-13 n: nnnnnnnnnnnhn\n" +
            "1-5 t: ztwwnt\n" +
            "8-9 z: zszzzzzbzzzz\n" +
            "1-5 p: pppppp\n" +
            "8-9 j: jjjjjbjkcjgj\n" +
            "5-6 x: xwhxlx\n" +
            "5-8 d: ddddwddx\n" +
            "5-17 l: lllztxdllwblllllv\n" +
            "9-18 m: mmgmmzmrmzchvrhqmm\n" +
            "17-18 c: wzsjwnccrgbcwhrmgc\n" +
            "10-17 f: fbdmffffchfcfkfft\n" +
            "17-18 r: rzbzrszcnnrmlrrrzk\n" +
            "1-9 p: cppppppppppp\n" +
            "1-9 t: ttptqthtttct\n" +
            "5-7 c: ncwnhmswscrqgtjtdgcr\n" +
            "5-10 f: dffsfffpffhzf\n" +
            "8-19 n: mnscfmjnnlvznnvlktn\n" +
            "7-8 z: zzzzxzzd\n" +
            "8-18 z: lzzbzbczzhdkzzwzgzz\n" +
            "1-9 x: rxxsxxxxxxxfxxxx\n" +
            "5-10 w: kjrwwptbww\n" +
            "12-13 z: zzzfzzzrzzzzz\n" +
            "5-6 g: gghggg\n" +
            "16-18 q: qqqqqqqqqqqlqqqqqxqq\n" +
            "5-9 c: lmcsxccccqjhmtcq\n" +
            "1-3 x: xxtnxfqzxxx\n" +
            "13-15 w: wddxxwwgqwwxwwww\n" +
            "12-16 r: mrrjmrrrhrrrrrrrrr\n" +
            "18-19 j: nmfjvcjljptwjnjjjjj\n" +
            "1-13 g: ggggggggggggggg\n" +
            "11-15 p: tpldppcbbbpzpvppw\n" +
            "2-11 x: hbxdxxgnqxbxxxxjjxx\n" +
            "9-11 s: nsnsksshzsqss\n" +
            "1-16 k: knkkfkkqkhhbkppvkk\n" +
            "2-4 x: tlwd\n" +
            "5-7 h: npmhclh\n" +
            "15-17 t: ttttttttttttttsttt\n" +
            "5-6 d: dxddrkddhdl\n" +
            "8-12 d: bddjdffdddtkgdhddd\n" +
            "7-8 z: dkxzgbzzlw\n" +
            "3-4 z: pzzz\n" +
            "5-6 t: ttttqvv\n" +
            "2-7 d: tpsdkqds\n" +
            "18-19 c: cccccccccccccccccbcc\n" +
            "2-3 c: hcmj\n" +
            "5-6 l: llllwl\n" +
            "2-6 t: tqtttx\n" +
            "11-12 r: rrrfrrrvrrrcrrrrrrr\n" +
            "9-12 s: dspssssshssssss\n" +
            "1-3 d: ddddc\n" +
            "4-5 t: tbpttzvtqr\n" +
            "4-6 j: jjgjdjj\n" +
            "2-4 t: tbtb\n" +
            "4-5 w: wbwbwwvww\n" +
            "10-11 s: dwsspssssssss\n" +
            "1-8 s: tssssssl\n" +
            "6-8 k: kksgmgkq\n" +
            "6-11 p: pppppppjcpq\n" +
            "7-8 c: ggcccpcclr\n" +
            "13-14 h: hhhhhhhhhhhhbfh\n" +
            "14-15 n: hsnnnnnnnnbnnwmnnn\n" +
            "11-13 k: xxmqpkkcqkkjn\n" +
            "12-14 w: qwkwwwxqwwzwcw\n" +
            "1-17 n: nnnnnfnnvnnnnnnrpnn\n" +
            "2-3 b: xbsgcgnrh\n" +
            "4-5 v: ckpfvkvvswdnh\n" +
            "6-7 q: qqqfqqf\n" +
            "8-10 m: vntcbkgmmm\n" +
            "9-13 m: bvxrzxbmlnmxcvmrwrc\n" +
            "4-5 j: fjjlj\n" +
            "1-3 k: lkskjkkc\n" +
            "8-14 d: ftbhrdxmmfdbkwrsqr\n" +
            "1-6 q: qrwcqqmtsqqhq\n" +
            "16-17 h: zlmjqfbxhhhfmpvsdg\n" +
            "3-8 v: bpwnbflvsljdzfkdmv\n" +
            "8-18 m: mskwllxmbgbrdjmhwmn\n" +
            "9-10 h: hhhhhzhhhq\n" +
            "6-8 t: jttttztv\n" +
            "2-4 m: xmmm\n" +
            "15-17 f: ffffffffffffffjfwfff\n" +
            "3-5 q: xrqqq\n" +
            "1-4 h: hhqfmhhh\n" +
            "14-15 f: ffffffffffhfcffd\n" +
            "2-11 w: fjjnmtswwwbhwcrgjwgd\n" +
            "4-9 q: qqqqqhqxqqxqt\n" +
            "8-11 g: gggggggcggggggggg\n" +
            "1-5 s: dbstvs\n" +
            "2-4 z: zzzgz\n" +
            "10-13 r: rrrrrrrrrrrrr\n" +
            "3-4 r: wrzr\n" +
            "5-9 c: cccddcrfccc\n" +
            "2-8 k: vkkvlgvvsqzzkkvnk\n" +
            "8-9 d: djdxdddwxdqrd\n" +
            "5-7 j: cjjpjggqhjwtth\n" +
            "5-15 n: nmnbnmnrxnrkznnvnn\n" +
            "3-13 j: cjjjjvgjqdjjdqjr\n" +
            "6-7 r: rzkrrvr\n" +
            "3-5 v: nvczvzgrnk\n" +
            "6-7 x: xxxxxdv\n" +
            "2-5 c: hccpcw\n" +
            "9-16 d: ddddddddddddddddd\n" +
            "6-9 c: ccfccdpcqccccp\n" +
            "4-5 q: kqtqq\n" +
            "1-2 z: zzzk\n" +
            "9-13 d: ddddddddddddd\n" +
            "5-8 q: prfjgqvzqbqqqq\n" +
            "2-6 h: rhrvghkfx\n" +
            "3-10 d: rddszpfmrdfgqt\n" +
            "7-11 w: wwvwwwkwwwlwwwwwww\n" +
            "7-9 b: bbbbbbbbm\n" +
            "1-2 r: ffnppzhtrkj\n" +
            "1-10 m: mxnmfmlkwmwpkj\n" +
            "3-10 n: nnwmnxnxnnl\n" +
            "14-16 p: pppppppppppppfppp\n" +
            "1-2 m: mmgn\n" +
            "11-12 p: hpppppkpppppp\n" +
            "6-14 l: lfvlllscxnlpll\n" +
            "11-12 r: rrrbrdrrrrrm\n" +
            "3-6 w: wwwcgw\n" +
            "9-12 b: rbfhbqblnbbbbdb\n" +
            "5-6 m: hmmkmmqmkm\n" +
            "4-6 q: qclhqjqq\n" +
            "4-16 l: lllnpllllllllllblllr\n" +
            "4-5 m: nxcmmtmr\n" +
            "3-5 q: qmblr\n" +
            "4-5 m: mmmmm\n" +
            "16-17 b: bbbbbbbbbbbbbbbcbb\n" +
            "1-7 p: tjppppppppp\n" +
            "5-6 k: kkkksf\n" +
            "2-10 x: cxjbfjkwjxqwzjxcbq\n" +
            "2-5 t: tsjkfn\n" +
            "4-7 g: xgbcrst\n" +
            "4-5 x: xxxxxx\n" +
            "2-5 s: sszxb\n" +
            "4-12 k: wcrkhkgkzklkqkh\n" +
            "8-10 b: bbbbbbbnbn\n" +
            "2-7 k: fkzfkkkkkklk\n" +
            "4-8 w: wwwwwwwww\n" +
            "4-8 h: hhhhhhhjh\n" +
            "4-11 h: tgbhnnrzpshbjhq\n" +
            "6-7 b: bsbdqbbb\n" +
            "2-6 t: sqvtbgttbftt\n" +
            "2-7 c: mctjgnn\n" +
            "3-8 m: ktthpgrfmrqkcj\n" +
            "5-7 x: whcxpgxvfq\n" +
            "5-14 w: wwwwwwwwwwwwwww\n" +
            "2-14 m: nmbxjbsmfjhdxmswks\n" +
            "7-11 b: jbbprkhndbqclbb\n" +
            "5-7 f: ffbfhfq\n" +
            "6-10 z: zzzzzzzzzzzz\n" +
            "4-7 d: mkdddgdhdh\n" +
            "2-4 d: pkjd\n" +
            "5-7 c: ccctqptcccccc\n" +
            "15-16 h: hshfjthnhssrvdhb\n" +
            "4-5 b: bbbxb\n" +
            "5-12 l: llllmllllllnl\n" +
            "3-4 t: tbgt\n" +
            "5-9 w: wwvzwblwgwwwwvwww\n" +
            "3-4 g: mmggfggg\n" +
            "8-14 j: jnjjvjcjtmpjtjjxcpw\n" +
            "8-9 h: hhhhwhhpch\n" +
            "5-7 v: vvdzhcvv\n" +
            "16-17 v: vvvvvvvvvvvvvvvtq\n" +
            "12-18 s: sdcvjsfqtgnhcsmmsm\n" +
            "6-13 n: hnqglmrjfgdnnpvtjr\n" +
            "12-13 q: qmqqvqqqtqqvqqq\n" +
            "1-9 z: nzzzzzzzzzzzzzz\n" +
            "1-4 l: lllllll\n" +
            "15-17 j: jjjjjjjjjjqjjjpjhj\n" +
            "2-3 t: bttb\n" +
            "3-4 q: qqqx\n" +
            "1-3 t: wtjt\n" +
            "18-19 x: xgnmxxljxwxxztxjvxx\n" +
            "2-4 n: pkpf\n" +
            "17-19 s: sssvssssssssssssssss\n" +
            "13-14 l: llqlllllllllll\n" +
            "5-9 m: mxgnmmrdmzll\n" +
            "3-5 m: mmcmmmmwmmm\n" +
            "4-8 b: bbbbbmplb\n" +
            "4-6 x: xxxxvx\n" +
            "1-2 m: lvfb\n" +
            "9-10 n: npnnnnnpnnnn\n" +
            "3-5 m: mmnmwmmmm\n" +
            "15-20 r: mwrrrrrrrwrrrrrrnrrr\n" +
            "1-2 l: rzlll\n" +
            "9-11 s: sssdssnssts\n" +
            "3-5 c: lccncc\n" +
            "13-14 v: vvvvvvvvvvvvvv\n" +
            "2-12 g: vshnfnhkzgjgkqn\n" +
            "6-9 k: kqskrckkwg\n" +
            "18-19 v: xzwbgvvnwlprqdxvshl\n" +
            "16-17 v: vvvvvvvvvvvvvvvzv\n" +
            "6-13 m: vkmmclmmwjfcvnmmm\n" +
            "5-11 j: sjjjqwjjrjjqj\n" +
            "5-7 q: djqhqcqhlz\n" +
            "8-9 f: fffmcfftw\n" +
            "12-14 x: xqpnjxjxlpxwxxb\n" +
            "7-16 h: hhhglhnhbcxhvhhxhh\n" +
            "12-13 v: vcvxvvvvvvvvvvv\n" +
            "12-13 g: ggdngtlxwlrtsgcgmtgm\n" +
            "5-6 n: nhnnhcn\n" +
            "3-4 n: nnngwk\n" +
            "9-10 k: kkkkkkpkkk\n" +
            "6-11 r: rrrrrkrrmrtr\n" +
            "3-9 d: dwdwdddqnfdddddddd\n" +
            "8-15 q: qvqqxqqwqrqqqfjq\n" +
            "6-7 f: ffffflf\n" +
            "4-9 m: rpmsmphdmmbpdmmhmpr\n" +
            "3-9 q: qqqqqqqqcq\n" +
            "3-4 d: hddds\n" +
            "2-4 f: rcfj\n" +
            "3-4 k: kkhn\n" +
            "6-9 n: npnnnnnlj\n" +
            "1-6 k: tvspqddqktkkqkvk\n" +
            "11-12 x: slxrptmpfqtp\n" +
            "12-14 l: jjvwhlldtlllllh\n" +
            "13-14 g: ngggggggggggks\n" +
            "14-15 z: zzzzzzzzzzzzzjvzz\n" +
            "5-6 l: vbsnvllnhlchblllc\n" +
            "7-13 z: zgczzbzgzlpnczzz\n" +
            "17-18 v: vvvvvvvvrvvvvvvvvvv\n" +
            "15-16 h: hhhhhhhhhghhhhhh\n" +
            "1-5 n: snnqv\n" +
            "6-7 m: mmmmmmmm\n" +
            "15-17 p: pppppppppppspqpppxp\n" +
            "12-14 w: wwwwwhwwwwwwwwwww\n" +
            "4-8 s: fssltbzbsrn\n" +
            "5-7 g: gkxgbggg\n" +
            "15-16 s: ssssssssssssssss\n" +
            "2-4 l: lxtswwg\n" +
            "5-6 p: plppzkpp\n" +
            "9-10 r: srrrprgrhrrrvrr\n" +
            "1-2 d: ddlhchdfll\n" +
            "3-4 j: jjwg\n" +
            "7-11 b: bkfbvbdvzlbz\n" +
            "7-13 q: qgvwkzkrkvvks\n" +
            "2-7 c: ccjtcbccccgv\n" +
            "2-3 q: fqqq\n" +
            "3-4 b: btssh\n" +
            "6-7 m: mnmmmmm\n" +
            "3-4 n: nrnn\n" +
            "5-14 n: fcsxngnnkqxnjnn\n" +
            "14-19 x: rmxcxxxxwxzxxhxxxlc\n" +
            "3-13 q: qqqqqgqmdshrqnqlqlqt\n" +
            "14-16 v: vvpvvvvvjvvnvvvvvvvv\n" +
            "15-16 c: cccccccccclcccch\n" +
            "4-6 v: hvvcvv\n" +
            "7-9 d: dcdmddxdld\n" +
            "16-18 x: rxxxxxxxzxxxxxxxdx\n" +
            "11-14 l: llcsqllgvfmhlvtvb\n" +
            "7-10 h: hhhhhdmhhwhhhh\n" +
            "5-17 g: ggggggggggggggggg\n" +
            "4-6 q: fbsnmzqdsqsqfpdr\n" +
            "12-16 n: fnnlvnflmcnndtfnlw\n" +
            "8-13 c: cpwshcvbccbjmlch\n" +
            "7-9 l: sfhcltwlc\n" +
            "9-13 w: xwwwwxwwwwwgwwkw\n" +
            "5-6 q: kqqqqqjqqqqqqk\n" +
            "14-17 k: kkkkkkkkcvbkkqxtkkkk\n" +
            "8-9 h: qjhxhjhzl\n" +
            "3-6 l: jlllvl\n" +
            "10-11 q: shkxnqwfrhhznlb\n" +
            "3-9 l: dwbvfgngtzcbhzlft\n" +
            "16-20 b: qstrwcrclxzbwtlbpnwb\n" +
            "8-10 n: ndhpptnnnjnnnbnn\n" +
            "4-8 l: lllnlllw\n" +
            "1-3 v: vdfxksvvn\n" +
            "14-17 b: blbbmbbbbbbbbbxbbbb\n" +
            "9-10 t: tttrkltgfbtth\n" +
            "10-12 n: njhnnnznnnnn\n" +
            "8-9 w: hfwwdwwww\n" +
            "4-5 c: scrcccwc\n" +
            "17-18 t: ttttttttttttttttmp\n" +
            "10-11 t: tttttttttvjtttttt\n" +
            "1-3 m: mdlrc\n" +
            "8-9 r: zrnjxkbrrppzgvf\n" +
            "3-4 d: sqddksgdjmd\n" +
            "3-5 m: mmmmmmm\n" +
            "1-8 h: nhclfdhlqwhhczn\n" +
            "2-7 c: bbcbccgxhcwn\n" +
            "4-6 l: zldqlgl\n" +
            "9-11 n: pqbxnxfzhtd\n" +
            "2-15 r: drmrjfxlqvmlcnwlbn\n" +
            "14-15 k: kkkskkkkkkkkktk\n" +
            "4-5 x: mxxzsxxxxx\n" +
            "1-2 p: hhfwz\n" +
            "6-13 b: mbdbkbpbjbbcb\n" +
            "12-16 t: tthfzkrqvhltzhlttwtw\n" +
            "6-11 h: hhhhhhhhhchzh\n" +
            "3-8 q: knndgrkmnqqxjj\n" +
            "5-7 v: svkvhfvv\n" +
            "6-9 r: rrrrrwrrrrr\n" +
            "3-10 p: pspxqhpxfqp\n" +
            "3-9 z: xfzzmjgqzgjzczqpnj\n" +
            "6-10 n: nnnncrnnnqnnnnn\n" +
            "1-7 k: kkkkkkkkk\n" +
            "2-4 m: mhmj\n" +
            "3-7 j: qjtjjmbjjkfjjrj\n" +
            "2-7 r: nrdxvnr\n" +
            "1-2 l: wrrr\n" +
            "3-4 t: ttjktt\n" +
            "9-13 l: lllllllclslllll\n" +
            "12-19 p: cpplpppphpppppdpntp\n" +
            "10-12 p: dnpppppppwpgpppp\n" +
            "2-4 z: pzzb\n" +
            "1-2 k: kpkt\n" +
            "4-7 r: rrrrrrq\n" +
            "1-7 t: xttwtnqttd\n" +
            "1-4 g: zngs\n" +
            "4-6 d: qszrkcxxdt\n" +
            "1-6 b: cpbhfm\n" +
            "3-4 m: knmn\n" +
            "9-11 c: lpdbchcckwnrc\n" +
            "3-4 r: rrrrr\n" +
            "12-18 q: qzqqwqqqqxrqqwqqqdqq\n" +
            "6-9 v: wvvvvpvbq\n" +
            "6-7 g: sggxxdhl\n" +
            "12-17 b: mbsgqwvzlnjskhxctt\n" +
            "4-5 f: rsfkc\n" +
            "9-12 h: hhhhhhhhshhhhhh\n" +
            "4-5 p: nppcn\n" +
            "3-5 g: ggwsmggsgggfg\n" +
            "4-6 p: gppfpsh\n" +
            "13-14 v: fvftvjtqvxsqhzrv\n" +
            "2-3 l: jlmbl\n" +
            "2-4 v: wwjvv\n" +
            "4-8 l: lllhlhllmlplg\n" +
            "1-14 f: znvtwnmslnfhjrds\n" +
            "3-10 z: zzhzkhzzlkdxzzz\n" +
            "17-19 r: rrrrrrrrrrrrrrrrrrrr\n" +
            "15-16 q: qpvqdgqkqqqqqqqq\n" +
            "5-12 k: wkkkkknkszpkkrk\n" +
            "3-8 j: jjhjjjjwj\n" +
            "2-12 s: qvknfbrpsrfsp\n" +
            "11-12 j: jjjjjjlfjjcrzjtj\n" +
            "3-13 m: mmmmglpmhtrfvmfmmmx\n" +
            "6-17 l: lllllblllllllllldll\n" +
            "4-5 q: rqqnqqqqq\n" +
            "8-9 p: fppppnspp\n" +
            "11-17 q: pqqqqqqqqqjqlqqqqd\n" +
            "3-4 l: lslll\n" +
            "1-10 r: bgrrrrrrrprrr\n" +
            "12-17 g: gggwjnxgmggngggrgpg\n" +
            "14-16 z: zxzzzzzzzzzzzpzgz\n" +
            "4-12 t: sttttttttttttwtz\n" +
            "6-7 x: xlzxxxxg\n" +
            "3-4 g: ggcg\n" +
            "3-11 c: zblkwrxvcnl\n" +
            "3-16 l: lhlljbljsllfhlklrlv\n" +
            "8-9 v: vvvvvvvvtp\n" +
            "2-5 f: fpbqcglx\n" +
            "3-15 g: cwmgbgntbgwccqggpv\n" +
            "4-11 m: mwwfhdgxdsmxckqcqvpg\n" +
            "12-14 v: vvpvvvvvvvvfnwvv\n" +
            "2-4 b: bbsxbwqbbx\n" +
            "4-7 s: knsnxlsmg\n" +
            "3-4 z: zzzzz\n" +
            "1-4 x: mxxxxxxx\n" +
            "2-7 w: pxwmtbkskmmfcddczqd\n" +
            "9-12 b: bbbbbqlbgbbb\n" +
            "3-4 l: mlqrlchqn\n" +
            "2-3 b: bbbb\n" +
            "13-15 x: lxxfjvqxhxhlxxx\n" +
            "5-8 m: mtmnkvmcm\n" +
            "3-7 v: xvwvvvwbtvs\n" +
            "2-16 x: wsbhsvzxbjfjwlzlzr\n" +
            "3-4 d: dzrd\n" +
            "5-7 l: llllllml\n" +
            "14-15 d: dddddddddddddwb\n" +
            "6-7 t: ttttfbttg\n" +
            "11-12 v: vvvvvvvvvvvvvvvv\n" +
            "11-14 z: zzzzzlzzzzdfvjtzk\n" +
            "4-20 b: jfnnqxxvxwhbfmbxqdxq\n" +
            "6-9 d: dddddzdddd\n" +
            "1-2 s: rnwsscss\n" +
            "2-3 q: kqkrhq\n" +
            "8-16 r: krlrxhrchrrrrvrkr\n" +
            "5-7 r: svcrrfq\n" +
            "2-13 b: bbbbbbbbbbbbbbs\n" +
            "3-7 k: pdxkstw\n" +
            "9-16 w: wwwwwwwwvwwwgwwww\n" +
            "3-5 g: gbgkggpcmjgrc\n" +
            "13-15 d: dddmdddmdddmldg\n" +
            "3-17 t: tkpttktttbttttttt\n" +
            "1-5 n: pnnngnnn\n" +
            "3-4 f: ffhf\n" +
            "3-7 p: tqpnncpczlp\n" +
            "4-13 b: ppbnsfztshmbbggn\n" +
            "1-4 r: rvlrrqrrrt\n" +
            "4-8 s: snfwsssrsrrssssszp\n" +
            "1-7 w: fwwwwwww\n" +
            "1-4 d: fdjb\n" +
            "7-8 l: llglthmjvlllt\n" +
            "7-8 w: wwwwwwzjw\n" +
            "7-9 v: zrgvvvvvvv\n" +
            "2-7 d: pdddzvh\n" +
            "2-9 w: nwwwbjswwxwxczlmh\n" +
            "5-10 w: wwcwwwwfwwghwbw\n" +
            "6-8 n: dqgnqjnnnnn\n" +
            "4-14 r: rdrfrrrrrrrrrvrrr\n" +
            "10-11 d: ddddddghtdfdhd\n" +
            "2-6 n: gngqzn\n" +
            "6-7 f: ffffdff\n" +
            "5-9 b: bbbbwbbbzb\n" +
            "7-9 n: knnnngnfnnn\n" +
            "8-14 b: gbnbsdbwcwdbvb\n" +
            "6-9 w: nttwjwbmw\n" +
            "3-13 c: gswwmvqdchfcgfrqcn\n" +
            "11-12 k: kzkvhkfrjxxjv\n" +
            "3-9 d: xdzkdgfdrx\n" +
            "6-13 q: qqqqcqqqqqqqqqq\n" +
            "7-9 b: bmbbbbbbb\n" +
            "8-16 p: hppgwpbmppcppppd\n" +
            "9-12 m: mwmmscmmdmpkmmm\n" +
            "3-6 n: nnnnnnn\n" +
            "3-16 f: lfqfhfffdfffszfkh\n" +
            "12-13 f: ffffffffffffmftffxf\n" +
            "1-5 k: kkkqk\n" +
            "3-6 f: ffsgft\n" +
            "2-9 z: ktzvzztzzrzzfnk\n" +
            "4-7 p: pppppgp\n" +
            "5-9 j: jgtjkvjhtjmvtc\n" +
            "4-5 g: ngngw\n" +
            "5-6 f: ffffcgf\n" +
            "3-11 k: xkkkcvwkkck\n" +
            "7-11 c: qcccpchcccc\n" +
            "3-17 h: hhnhhhhhhhhhhhhhhh\n" +
            "4-5 x: bxjxj\n" +
            "18-19 v: vbvcvvvcwvvvvvvvvtn\n" +
            "12-14 d: dddddddddddwdxddd\n" +
            "6-10 b: bbbbbbbbbbbb\n" +
            "1-4 f: pfjf\n" +
            "1-8 b: bbbbbbltbbbbbb\n" +
            "14-15 d: dzddkfqcdxwfdnd\n" +
            "8-10 t: tvxwlxltjt\n" +
            "7-9 l: lxklrwlhl\n" +
            "3-6 c: cclccdc\n" +
            "15-17 w: wdwwwwwwwwxwwwqwfw\n" +
            "1-4 h: ngkhh\n" +
            "3-4 j: jjjj\n" +
            "4-9 h: nphhzhhmhgb\n" +
            "5-10 v: tsxzvvdvmvvsvp\n" +
            "1-11 r: frjgrqrrrrkrrmrl\n" +
            "10-12 p: zlkppppppmxppphsgd\n" +
            "5-8 p: stmggpsmx\n" +
            "3-5 r: rrrrrrrrrrrrrr\n" +
            "2-3 t: ttgt\n" +
            "6-11 m: mmjmsmhmmsmdmfmvm\n" +
            "6-8 s: pnkbhsfsfgsr\n" +
            "7-13 t: gchcvtttwgkmlbw\n" +
            "8-11 l: lllllllrllrlh\n" +
            "5-7 d: djvddzdd\n" +
            "3-4 z: zzzzkk\n" +
            "5-11 s: wsbdskxssjtqcs\n" +
            "2-3 w: wwwszj\n" +
            "1-4 m: mmvm\n" +
            "3-9 x: bkzkrvkjfbtxn\n" +
            "5-6 z: zzzzzwz\n" +
            "1-4 v: vvvrvv\n" +
            "1-4 d: zdxd\n" +
            "6-8 k: klfnzkrswq\n" +
            "1-6 p: pkjpcpntjzvp\n" +
            "14-16 p: pdpppqmpmppqppppgp\n" +
            "9-10 w: wwvglrwkrbwwwkwzww\n" +
            "3-6 v: vfdvvcsvv\n" +
            "9-13 z: zzzzzzbzzgfzzzzzczz\n" +
            "4-5 n: nnnqnn\n" +
            "4-13 m: jmbmmmmmmmnmmmvmm\n" +
            "2-10 r: rlrcrrdnkrkrsqr\n" +
            "9-14 r: rzrgrrrrhrrbrsrr\n" +
            "9-11 f: ffpffzfvffzf\n" +
            "10-11 j: jzjjjjzfpjjjrsgjjt\n" +
            "3-4 b: bbbnbb\n" +
            "4-6 z: zgzwzqhq\n" +
            "10-11 j: jjxjxhjjjwj\n" +
            "4-5 b: bbbbb\n" +
            "4-5 d: dbzhw\n" +
            "2-8 r: rrrlrrrrgrgfrwdf\n" +
            "1-5 q: qmtrq\n" +
            "9-13 j: jkjjjjjjjzjjt\n" +
            "3-7 j: rjjjjjjjm\n" +
            "5-9 z: zzzzdzzznzz\n" +
            "2-13 t: tjtttttttfttsttt\n" +
            "12-13 d: kbddmmkmcwdkddw\n" +
            "3-4 q: qqql\n" +
            "5-6 j: jjjjsqjj\n" +
            "1-2 b: bbgwqt\n" +
            "3-11 t: tftjtttttttttt\n" +
            "9-12 h: hjxhhhhhqhhzz\n" +
            "1-2 m: ncmmmml\n" +
            "1-3 x: qxxs\n" +
            "1-7 t: dtstrnxttt\n" +
            "11-13 q: qqdqqpjjqktqbqnqqq\n" +
            "2-5 p: pppppp\n" +
            "2-4 n: njdjzpnghzbgvnngqn\n" +
            "11-12 g: lpfwcvsqgmggfrjmdvs\n" +
            "1-7 n: hrwhnvrmm\n" +
            "12-13 s: hssdssscsgsksjssss\n" +
            "3-8 x: csxgdxkxxptmlw\n" +
            "9-11 q: qqqqqqnqkqmqqqqq\n" +
            "3-4 g: wzkf\n" +
            "7-8 t: cktttttt\n" +
            "4-12 c: fgdjrccpmhcccwcgfm\n" +
            "6-8 p: jppppppt\n" +
            "1-4 p: pppppr\n" +
            "1-7 n: nnrrrtndwn\n" +
            "1-6 l: rldlkq\n" +
            "2-4 x: rglr\n" +
            "2-7 p: vpvmkgp\n" +
            "4-5 n: nnnnz\n" +
            "5-18 w: txgfflhvtdpdvwlwmmq\n" +
            "9-10 l: tlllllllddl\n" +
            "1-3 b: xpzbbbrbbr\n" +
            "3-5 n: npnpnn\n" +
            "10-14 q: nqqqqqqqqqqqqqqdqx\n" +
            "7-10 w: bdwwwwgwljxgv\n" +
            "7-11 k: kwknkkdlzkk\n" +
            "1-10 w: wsjbvzwslmwttq\n" +
            "15-18 b: bbbbbbbcbbbrbbbbbbb\n" +
            "6-8 j: jdjjnlfj\n" +
            "10-11 r: xrgrrrrrnvwrrfrr\n" +
            "11-15 x: xxxxxxxxxxxxxxjx\n" +
            "5-10 w: wfwwnwvngwlwwlw\n" +
            "2-4 k: kkkk\n" +
            "3-5 h: hjhhh\n" +
            "7-8 s: lqsssscjrss\n" +
            "10-12 t: tttsttttttttg\n" +
            "3-8 p: szpsqzqp\n" +
            "3-8 x: xxxxxxxxx\n" +
            "6-7 r: rrxrrdrr\n" +
            "1-2 b: zbbbbbbbbbbbbb\n" +
            "3-6 v: vxvkvv\n" +
            "4-5 w: wwwwwwdw\n" +
            "3-5 n: nnfnn\n" +
            "11-12 g: gggggggvggxgg\n" +
            "10-12 s: sssqssssssssns\n" +
            "3-7 h: hlmhhhhhhh\n" +
            "7-8 v: vsdcvkvvszzm\n" +
            "6-9 g: ggwnldgws\n" +
            "14-15 q: qqqqkqqqqqqqkwkq\n" +
            "8-9 l: bttjllqhnqjdvhsnk\n" +
            "10-11 s: sqsscsqsscts\n" +
            "10-14 h: hjhxhhhnhhxglkhvzl\n" +
            "3-6 r: krrnvr\n" +
            "12-17 z: zzsfzzzjzzzrzhzzgh\n" +
            "1-5 b: bdnmb\n" +
            "18-19 c: cccccccccccccccccckc\n" +
            "13-16 t: tttttttrtttcdttpt\n" +
            "5-6 c: ccczlxc\n" +
            "2-7 b: phbqtkkkdglk\n" +
            "4-6 x: tgrmqlxwgrgwxmkfr\n" +
            "2-7 p: xspljfg\n" +
            "4-9 b: bbbwbbbbmbbb\n" +
            "3-9 b: brbvbbxqb\n" +
            "13-14 c: cccpckqscbcchc\n" +
            "1-3 m: mmmm\n" +
            "1-2 v: bvvvvc\n" +
            "2-3 b: bbsbbbnbbb\n" +
            "1-2 f: gkfms\n" +
            "5-6 n: nnnnnq\n" +
            "4-5 c: kffccnrmn\n" +
            "1-6 b: slgwbm\n" +
            "2-3 x: mxcj\n" +
            "3-4 p: gpbqpfsp\n" +
            "5-8 s: szwszsss\n" +
            "5-6 g: zkgjggg\n" +
            "3-10 v: twmqbvvnvv\n" +
            "3-5 z: shlzs\n" +
            "1-6 r: wrrljrfntswb\n" +
            "2-7 j: jjjjjjjjjj\n" +
            "4-5 f: jfffqw\n" +
            "1-3 r: kwrrrrfwp\n" +
            "2-9 c: ccmcrthdqtk\n" +
            "13-15 w: wwwwwwwwwwwwrwwww\n" +
            "14-15 s: ssssssssssssssss\n" +
            "2-5 r: rhmrfmr\n" +
            "6-7 x: dwxgfpsbtvx\n" +
            "7-8 b: bbbbcbbb\n" +
            "1-5 l: slllcqlll\n" +
            "3-4 h: hhbr\n" +
            "3-6 k: kkkpkkk\n" +
            "2-5 s: nsssmsssbs\n" +
            "7-8 s: xtxtwtzspxsszmgjlpzx\n" +
            "2-4 r: jzqc\n" +
            "9-10 h: hhhhhhhbwh\n" +
            "8-13 g: xgzjgjgggggmgggzc\n" +
            "1-10 j: lrhzsjmfrzz\n" +
            "4-10 z: dkqdhhrszpcplmfqgg\n" +
            "7-9 x: xxxxxxwxxx\n" +
            "12-13 f: fffpfqcfbkdvsbtzwwf\n" +
            "5-8 g: ghsvggggzgggg\n" +
            "10-14 z: ctzzkszzzlzmzzzz\n" +
            "2-4 d: xfwdd\n" +
            "9-15 j: xjjdjcjhnjjjfjjj\n" +
            "1-2 h: hhhhhgwjhznh\n" +
            "9-13 d: kddddbdddxddjsdsdd\n" +
            "7-9 x: rxxxxdwxxxxnxkxcx\n" +
            "6-16 r: rlrtlkdftfgqpkrsljr\n" +
            "1-3 z: pzzz\n" +
            "5-6 h: krhbsh\n" +
            "8-9 x: mxqhpmqglxxwxqwxxxp\n" +
            "2-4 z: vmfj\n" +
            "12-15 s: sssfsssssksssst\n" +
            "3-5 f: fwhfb\n" +
            "10-12 j: jjjjjzwjjjjw\n" +
            "4-6 j: jjjjjjjjjjj\n" +
            "11-12 k: kkkkvfktkkkkkkwwzknk\n" +
            "5-8 m: mhhmbvmvms\n" +
            "10-14 r: rlwrdfzkhgrcrlz\n" +
            "5-6 h: hhhhfh\n" +
            "2-4 w: wwqhwww\n" +
            "1-5 x: nxxxwxx\n" +
            "11-16 h: xpshnhxbwclbhrhwsh\n" +
            "7-9 t: ttttflgtkh\n" +
            "10-20 n: bnknnnnnnlnnnnmnvncn\n" +
            "2-5 w: pwwhwkq\n" +
            "1-5 j: jhjjj\n" +
            "5-6 f: fzffzfwfr\n" +
            "3-6 s: sssssgs\n" +
            "9-10 w: wwwwwnwxbrww\n" +
            "5-6 z: xzzhzjzzzzhzhz\n" +
            "17-18 v: vvvvvvvvvvvvvvvtvbv\n" +
            "13-20 l: llllldllllllllllllll\n" +
            "8-14 k: kkkkkkkgkkkkkkkk\n" +
            "7-9 j: jjnjjjjjjj\n" +
            "7-14 j: tjbjljjrjjjjzjjjj\n" +
            "1-4 m: jcmmm\n" +
            "6-9 g: ggnggsghggg\n" +
            "2-16 v: pvvqdcrpzpsmppfvdftf\n" +
            "8-11 j: jjjjjjjjjvj\n" +
            "4-6 m: qbmmxmjpm\n" +
            "2-12 l: pllqdxmwfmmlmznqr\n" +
            "3-4 b: bsbhbbbbb\n" +
            "1-4 w: wwww\n" +
            "1-11 r: rrrrjrrrgmrr\n" +
            "3-8 t: tnrztcht\n" +
            "3-14 p: pjppkpplsphlpn\n" +
            "7-8 j: tdfcjdjbjjjvjj\n" +
            "10-11 n: nnnnnnmhnnnnrddrnn\n" +
            "1-7 p: tppgqppptqscprnp\n" +
            "3-4 c: cqcmcc\n" +
            "2-8 l: llllllrlll\n" +
            "9-12 j: dmcwsjjrvmzjp\n" +
            "4-8 h: hhhrhhhb\n" +
            "1-5 n: nnnnnn\n" +
            "5-6 s: srssss\n" +
            "2-8 n: nrbngnntnnn\n" +
            "1-13 f: bffmjfdfffffp\n" +
            "7-8 t: tqtttttt\n" +
            "3-4 x: xxhh\n" +
            "15-18 j: jjjjjjjjjjjjjjpjjk\n" +
            "7-9 v: vkvvmzvvv\n" +
            "5-7 j: xjjgkjknjjp\n" +
            "2-4 l: llslkh\n" +
            "10-11 m: mmmmmmmmmjwmmmwmm\n" +
            "5-6 j: pjjzjqbqv\n" +
            "5-11 n: nnnncnnnnnfnnnnnn\n" +
            "2-13 g: gdfrmlcszxcwj\n" +
            "9-16 b: bbbbbbwhpztbhdbzb\n" +
            "1-4 f: fffffc\n" +
            "1-3 f: fffkf\n" +
            "16-17 p: pppppppppppppppkt\n" +
            "6-10 h: wzcnzhvhml\n" +
            "1-9 f: ffffffffff\n" +
            "3-8 f: kffgggng\n" +
            "8-13 m: mmmmmmmmmmmmmm\n" +
            "12-19 k: zkzzlkkvpnllksklljr\n" +
            "1-4 j: jjmjjjjxjwj\n" +
            "4-5 h: phhhhzhhhmhhprh\n" +
            "11-12 p: ppppppppppvppp\n" +
            "13-16 j: hpgjjjwfhjgmdttl\n" +
            "2-4 w: wwjwhthzhvpmpfkw\n" +
            "9-10 k: kkxkkkkskkv\n" +
            "17-20 j: jjjjjjbjjjzjjjjjjjjj\n" +
            "1-3 v: cvvvb\n" +
            "5-8 s: zbnmbfgdp\n" +
            "10-11 x: xxxxgmdtxxtxxxbx\n" +
            "12-17 n: nmnnjcndnndcnncnnrnn\n" +
            "3-6 p: lmblxwpjvfgjps\n" +
            "9-12 s: ssssssssfsssw\n" +
            "9-10 g: ggggggwgkzgggg\n" +
            "5-12 m: pzmmmfxgvmtmlmq\n" +
            "2-7 p: ptppprn\n" +
            "9-10 c: bgqtkccxcqb\n" +
            "8-11 r: rdrrrrrhrrmr\n" +
            "7-9 w: wwqwwwfwwjwhgrw\n" +
            "5-7 r: rrrrrrh\n" +
            "2-10 s: rsflsvlwfs\n" +
            "3-7 b: bbqbbbb\n" +
            "11-12 m: mmjmmqmnmmmm\n" +
            "7-13 h: hhhhhhphhhnhghh\n" +
            "12-13 b: bbbbbbblbbbtk\n" +
            "5-13 h: ppgzjhhhlhhqx\n" +
            "14-19 q: qlbqmqqqjqqqqrqkjnq\n" +
            "3-19 f: pxmznsfdhzjqrdfjqrd\n" +
            "16-17 q: qqmdqrqqxcqfxfgjg\n" +
            "12-13 j: njjjzjghjjjjc\n" +
            "9-11 l: vmbsllkcshmrhklrl\n" +
            "1-2 c: tccccc\n" +
            "3-6 p: jspprpjxhn\n" +
            "5-8 x: xrxzxfwxxx\n" +
            "9-10 z: zdznzzzzzzzgzz\n" +
            "4-5 j: jjpjq\n" +
            "4-6 r: rcxscm\n" +
            "2-6 k: pkqjskrlfknnrqt\n" +
            "3-11 k: bqbskncdkfrphshvv\n" +
            "11-13 g: ggqgggggggggggg\n" +
            "6-14 f: fffdxmfffjfffmffff\n" +
            "19-20 z: zzzznzzzzzzzzzzzzzzz\n" +
            "5-8 j: jjjjjjjjjgjjjjjjjjj\n" +
            "2-4 k: pkbkqpsrgkcwc\n" +
            "8-12 b: dbbwtbwbqxvbwrbl\n" +
            "1-8 v: rvrvfcnlcwflcvlsv\n" +
            "4-5 f: hffhfkq\n" +
            "3-12 g: zggpngtnvzgd\n" +
            "4-8 t: ttttwrwt\n" +
            "12-13 x: xxxxxxxvxxxdnx\n" +
            "9-12 j: jrvjjjjjbjjp\n" +
            "1-13 b: zbhbbbbbbbbbvbb\n" +
            "1-2 w: wwwwwww\n" +
            "15-16 k: tfkxskmvqlkkmfkj\n" +
            "12-18 b: bdpxktjwpxhsbgmrfb\n" +
            "8-10 v: vvvvvvtzvzvv\n" +
            "18-19 g: ggglgggggggggggggggg\n" +
            "4-8 s: pnzsjvwsmxwgrjmsm\n" +
            "14-17 p: pppppxppppppppprpkp\n" +
            "9-17 n: nvlnqnwnnnztfcgnpdn\n" +
            "3-5 l: mlqflfl\n" +
            "7-11 z: dzzzzdmnzznzvzzz\n" +
            "14-16 r: xrrsvrhhrlnjjrvrr\n" +
            "12-14 z: vnwzqsvvtdnpvvdrhgz\n" +
            "1-4 h: mhhhh\n" +
            "1-5 m: pmmmmmm\n" +
            "6-11 j: jmkljhjjvjmfmjpj\n" +
            "2-4 f: xhtkdf\n" +
            "5-14 x: frqqxljjwsxndx";
}
